FROM alpine:3.15.0

LABEL version="1.0.0" maintainer="Mohamed BARRY" os="linux"

ENV CONTAINER_USER='BARRY'

#RUN echo $CONTAINER_USER > ./BARRY
RUN unset CONTAINER_USER

CMD ["hello-alpine, I’m Mohamed and this is a container from my first image"]
